### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by bhaskardabhi-oviyum** [baw/atom-hide-files#11]
[steps to reproduce:]

1. Install Plugin
2. Click Shift + Command + H

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [hide-files](https://github.com/imamathwiz/atom-hide-files) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'contains' of undefined

```
At /Users/bhaskardabhi/.atom/packages/hide-files/lib/hide_items.coffee:37

TypeError: Cannot read property 'contains' of undefined
    at HideItems.getParentDirectory (/packages/hide-files/lib/hide_items.coffee:37:26)
    at HideItems.loopThroughParents (/packages/hide-files/lib/hide_items.coffee:66:15)
    at HideItems.addParentExpandEvents (/packages/hide-files/lib/hide_items.coffee:12:6)
    at HideItems.hideItemCommand (/packages/hide-files/lib/hide_items.coffee:60:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:43.9.0 core:close (input.hidden-input)
     -2:50.6.0 settings-view:open (div.tool-panel.tree-view)
     -2:45.7.0 core:confirm (input.hidden-input)
  2x -0:14.9.0 hide-files:hide-file (atom-pane.pane)
```

### Non-Core Packages

```
atom-asana 0.0.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-laravel-log 0.0.0 
atom-ternjs 0.18.3 
atom-translator 0.2.1 
data-atom 0.25.2 
emmet 2.4.3 
git-time-machine 1.5.9 
gpp-compiler 3.0.7 
hide-files 0.2.0 
highlight-selected 0.13.1 
merge-conflicts 1.4.5 
minimap-highlight-selected 4.6.1 
php-cs-fixer 4.1.0 
phpfmt 1.0.0 
termination 0.6.0 
```

**Comment by baw** [comment]
fixed with fa7bbf0a4df2107aab97671c30822733252dbba4
released in version 0.3.0
