### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by manxboy** [baw/atom-hide-files#13]
[Enter steps to reproduce:]

1. Select File in tree view
2. press command shift H
3. file gets hidden but error is thrown

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [hide-files](https://github.com/imamathwiz/atom-hide-files) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'contains' of undefined

```
At /Users/dvfsusstudent/.atom/packages/hide-files/lib/hide_items.coffee:37

TypeError: Cannot read property 'contains' of undefined
    at HideItems.getParentDirectory (/packages/hide-files/lib/hide_items.coffee:37:26)
    at HideItems.loopThroughParents (/packages/hide-files/lib/hide_items.coffee:66:15)
    at HideItems.addParentExpandEvents (/packages/hide-files/lib/hide_items.coffee:12:6)
    at HideItems.hideItemCommand (/packages/hide-files/lib/hide_items.coffee:60:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:32.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  3x -0:17.3.0 hide-files:hide-file (span.name.icon.travis-icon.medium-red)
```

### Non-Core Packages

```
atom-clock 0.1.15 
chrome-color-picker 0.8.0 
file-icons 2.1.13 
hide-files 0.2.0 
mdn-doc 0.3.0 
```

**Comment by baw** [comment]
fixed with fa7bbf0a4df2107aab97671c30822733252dbba4
released in version 0.3.0
