### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by ChildishGiant** [baw/atom-hide-files#14]
1. Try to hide something using CTRL + SHIFT + H

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hide-files](https://github.com/imamathwiz/atom-hide-files) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'contains' of undefined

```
At C:\Users\Ali\.atom\packages\hide-files\lib\hide_items.coffee:37

TypeError: Cannot read property 'contains' of undefined
    at HideItems.getParentDirectory (/packages/hide-files/lib/hide_items.coffee:37:26)
    at HideItems.loopThroughParents (/packages/hide-files/lib/hide_items.coffee:66:15)
    at HideItems.addParentExpandEvents (/packages/hide-files/lib/hide_items.coffee:12:6)
    at HideItems.hideItemCommand (/packages/hide-files/lib/hide_items.coffee:60:8)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:22.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:28.5.0 settings-view:open (input.hidden-input)
     -1:26.4.0 core:paste (input.hidden-input)
     -1:25.9.0 core:confirm (input.hidden-input)
  2x -0:14.6.0 hide-files:hide-file (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.5 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-math 0.1.1 
autocomplete-python 1.10.5 
color-picker 2.2.5 
file-icons 2.1.14 
hide-files 0.2.0 
ide-python 0.3.0 
```

**Comment by baw** [comment]
fixed with fa7bbf0a4df2107aab97671c30822733252dbba4
released in version 0.3.0
