### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by Nazaretto** [baw/atom-hide-files#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [hide-files](https://github.com/imamathwiz/atom-hide-files) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'contains' of undefined

```
At C:\Users\Nazar\.atom\packages\hide-files\lib\hide_items.coffee:37

TypeError: Cannot read property 'contains' of undefined
    at HideItems.getParentDirectory (/packages/hide-files/lib/hide_items.coffee:37:26)
    at HideItems.loopThroughParents (/packages/hide-files/lib/hide_items.coffee:66:15)
    at HideItems.addParentExpandEvents (/packages/hide-files/lib/hide_items.coffee:12:6)
    at HideItems.hideItemCommand (/packages/hide-files/lib/hide_items.coffee:60:8)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -4:38.3.0 editor:newline (input.hidden-input)
     -4:37.9.0 core:paste (input.hidden-input)
     -4:24.5.0 core:backspace (input.hidden-input)
     -4:22 core:delete (input.hidden-input)
     -4:20.9.0 core:save (input.hidden-input)
     -3:22.8.0 core:confirm (input.hidden-input)
     -1:58.8.0 core:backspace (input.hidden-input)
  2x -1:43.3.0 hide-files:hide-file (div.tool-panel.tree-view)
     -0:59.5.0 hide-files:unhide-project-files (div.tool-panel.tree-view)
  2x -0:50.5.0 hide-files:hide-file (div.tool-panel.tree-view)
     -0:44.8.0 window:run-package-specs (div.tool-panel.tree-view)
  5x -0:24.1.0 hide-files:hide-file (div.tool-panel.tree-view)
```

### Non-Core Packages

```
hide-files 0.2.0 
open-in-browser 0.5.2 
terminal-plus 0.14.5 
```

**Comment by baw** [comment]
fixed with fa7bbf0a4df2107aab97671c30822733252dbba4
released in version 0.3.0
